version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./apps/backend/prisma:/app/apps/backend/prisma
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: file:./apps/backend/prisma/dev.db
      DATABASE_URL_TEMP: file:./apps/backend/prisma/dev.db

volumes:
  node_modules: {}
